# Generated by Django 3.2.5 on 2021-09-04 10:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hr', '0001_initial'),
        ('crm', '0001_initial'),
        ('utility', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('order_submitted', 'order_submitted'), ('shipping', 'shipping'), ('completed', 'completed'), ('back', 'back'), ('order_cancel', 'order_cancel')], max_length=32, verbose_name='وضعیت :')),
                ('billing_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.billingaddress', verbose_name='آدرس تنظیم صورت حساب :')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hr.employee', verbose_name='مشتری :')),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.customer', verbose_name='فروشنده :')),
                ('shipping_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.shippingaddress', verbose_name='آدرس ترابری :')),
            ],
            options={
                'verbose_name': 'خرید',
                'verbose_name_plural': 'خرید ها',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='نام :')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات :')),
                ('slug', models.CharField(blank=True, max_length=255, null=True, verbose_name='کد شماره صفحه :')),
                ('parent_category', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_item', to='inventory.category', verbose_name='دسته بندی سازمانی')),
            ],
            options={
                'verbose_name': 'طبقه بندی',
                'verbose_name_plural': 'طبقه بندی ها',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='نام :')),
                ('brand', models.CharField(blank=True, max_length=255, null=True, verbose_name='برند :')),
                ('model', models.CharField(blank=True, max_length=255, null=True, verbose_name='مدل :')),
                ('item_quantity', models.DecimalField(decimal_places=2, default='0.00', max_digits=12, verbose_name='مقدار موجود :')),
                ('orginal_price', models.DecimalField(decimal_places=2, default='0.00', max_digits=12, verbose_name='قیمت اصلی :')),
                ('sale_price', models.DecimalField(decimal_places=2, default='0.00', max_digits=12, verbose_name='قیمت فروش :')),
                ('date_added', django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='تاریخ اضافه شدن :')),
                ('slug', models.CharField(blank=True, max_length=255, null=True, verbose_name='کد شماره صفحه :')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.category', verbose_name='دسته بندی :')),
                ('item_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='utility.unit', verbose_name='واحد مربوط :')),
            ],
            options={
                'verbose_name': 'کالا',
                'verbose_name_plural': 'کالاها',
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', django_jalali.db.models.jDateTimeField(auto_now_add=True, null=True, verbose_name='ایجاد شده در تاریخ ')),
                ('modified_on', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تغییر داده شده در تاریخ ')),
                ('status', models.CharField(blank=True, choices=[('order_submitted', 'order_submitted'), ('shipping', 'shipping'), ('completed', 'completed'), ('back', 'back'), ('order_cancel', 'order_cancel')], max_length=32, verbose_name='وضعیت :')),
                ('billing_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.billingaddress', verbose_name='آدرس تنظیم صورت حساب :')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sale_createdby', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد شده توسط ')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.customer', verbose_name='مشتری :')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sale_modifiedby', to=settings.AUTH_USER_MODEL, verbose_name='تغییر داده شده توسط ')),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hr.employee', verbose_name='فروشنده :')),
                ('shipping_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.shippingaddress', verbose_name='آدرس ترابری :')),
            ],
            options={
                'verbose_name': 'فروش',
                'verbose_name_plural': 'فروش ها',
            },
        ),
        migrations.CreateModel(
            name='WareHouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', django_jalali.db.models.jDateTimeField(auto_now_add=True, null=True, verbose_name='ایجاد شده در تاریخ ')),
                ('modified_on', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تغییر داده شده در تاریخ ')),
                ('code', models.CharField(blank=True, max_length=255, null=True, verbose_name='کد :')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='نام :')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='موقعیت :')),
                ('date_start', django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='تاریخ شروع :')),
                ('date_end', django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='تاریخ پایان :')),
                ('status', models.CharField(blank=True, choices=[('active', 'active'), ('inactive', 'inactive')], max_length=32, verbose_name='وضعیت :')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_createdby', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد شده توسط ')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_modifiedby', to=settings.AUTH_USER_MODEL, verbose_name='تغییر داده شده توسط ')),
            ],
            options={
                'verbose_name': 'انبار کالا',
                'verbose_name_plural': 'انبار های کالا',
            },
        ),
        migrations.CreateModel(
            name='WareHouseManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointed_date', django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='تاریخ قرارداد :')),
                ('date_end', django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='تاریخ پایان :')),
                ('status', models.CharField(blank=True, choices=[('active', 'active'), ('inactive', 'inactive')], max_length=32, verbose_name='وضعیت :')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hr.employee', verbose_name='مدیر :')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.warehouse', verbose_name='انبار :')),
            ],
            options={
                'verbose_name': 'مدیریت انبار کالا',
                'verbose_name_plural': 'مدیریت انبار کالا',
            },
        ),
        migrations.CreateModel(
            name='SaleProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default='0.00', max_digits=12, verbose_name='مقدار :')),
                ('discount', models.DecimalField(decimal_places=2, default='0.00', max_digits=12, verbose_name='تخفیف :')),
                ('tax', models.DecimalField(decimal_places=2, default='0.00', max_digits=12, verbose_name='مالیات :')),
                ('date_added', django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='تاریخ اضافه شدن :')),
                ('slug', models.CharField(blank=True, max_length=255, null=True, verbose_name='کد شماره صفحه :')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.item', verbose_name='نوع جنس :')),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.sale', verbose_name='فروش :')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='utility.unit', verbose_name='واحد :')),
            ],
            options={
                'verbose_name': 'فروش',
                'verbose_name_plural': 'فروش ها',
            },
        ),
        migrations.AddField(
            model_name='item',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.warehouse', verbose_name='انبار :'),
        ),
        migrations.CreateModel(
            name='BuyProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default='0.00', max_digits=12, verbose_name='مقدار :')),
                ('discount', models.DecimalField(decimal_places=2, default='0.00', max_digits=12, verbose_name='تخفیف :')),
                ('tax', models.DecimalField(decimal_places=2, default='0.00', max_digits=12, verbose_name='مالیات :')),
                ('date_added', django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='تاریخ اضافه شدن :')),
                ('slug', models.CharField(blank=True, max_length=255, null=True, verbose_name='کد شماره صفحه :')),
                ('buy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.buy', verbose_name='خرید :')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.item', verbose_name='نوع جنس :')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='utility.unit', verbose_name='واحد :')),
            ],
            options={
                'verbose_name': 'خرید محصول',
                'verbose_name_plural': 'خرید محصول ها',
            },
        ),
    ]
