# Generated by Django 3.2.5 on 2021-09-04 10:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hr', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='نام ')),
                ('slug', models.CharField(blank=True, max_length=255, null=True, verbose_name='کد ')),
                ('parent_type', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prev_item', to='accounting.accounttype', verbose_name='نوع حساب سازمانی ')),
            ],
            options={
                'verbose_name': 'نوع حساب',
                'verbose_name_plural': 'انواع حساب',
            },
        ),
        migrations.CreateModel(
            name='AccountYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='نام ')),
                ('start_date', django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='تاریخ شروع ')),
                ('end_date', django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='تاریخ پایان ')),
                ('slug', models.CharField(blank=True, max_length=255, null=True, verbose_name='کد مرتبط ')),
            ],
            options={
                'verbose_name': 'حساب سالانه',
                'verbose_name_plural': 'حساب های سالانه',
            },
        ),
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=255, null=True, verbose_name='کد ')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='نام ')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات ')),
                ('total_debit', models.DecimalField(decimal_places=2, default='0.00', max_digits=12, verbose_name=' : مقدار کل بدهی ')),
                ('total_credit', models.DecimalField(decimal_places=2, default='0.00', max_digits=12, verbose_name='مقدار کل اعتبار ')),
                ('balance', models.DecimalField(decimal_places=2, default='0.00', max_digits=12, verbose_name='مانده ')),
                ('last_update_date', django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='آخرین بروز رسانی ')),
                ('account_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.accounttype', verbose_name='نوع حساب کاربری')),
            ],
            options={
                'verbose_name': 'دفتر کل',
                'verbose_name_plural': 'دفتر کل',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', django_jalali.db.models.jDateTimeField(auto_now_add=True, null=True, verbose_name='ایجاد شده در تاریخ ')),
                ('modified_on', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تغییر داده شده در تاریخ ')),
                ('trnsaction_type', models.CharField(blank=True, choices=[('General', 'General'), ('POS', 'POS')], max_length=32, verbose_name='نوع میادله ')),
                ('subject', models.CharField(blank=True, max_length=255, null=True, verbose_name='موضوع ')),
                ('ref_no', models.CharField(blank=True, max_length=255, null=True, verbose_name='شماره مرجع ')),
                ('voucher_no', models.CharField(blank=True, max_length=255, null=True, verbose_name='شماره ی ووچر ')),
                ('entry_date', django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='تاریخ وررد ')),
                ('post_status', models.CharField(blank=True, choices=[('pending', 'pending'), ('posted', 'posted')], max_length=32, verbose_name='وضعیت بعدی ')),
                ('account_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.accountyear', verbose_name='سال حساب کاربری ')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction_createdby', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد شده توسط ')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction_modifiedby', to=settings.AUTH_USER_MODEL, verbose_name='تغییر داده شده توسط ')),
            ],
            options={
                'verbose_name': 'مبادلات',
                'verbose_name_plural': 'مبادلات',
            },
        ),
        migrations.CreateModel(
            name='TransactionDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات :')),
                ('vat', models.DecimalField(decimal_places=2, default='0.00', max_digits=12, verbose_name='مالیات بر ارزش افزوده :')),
                ('tax', models.DecimalField(decimal_places=2, default='0.00', max_digits=12, verbose_name='مالیت :')),
                ('debit', models.DecimalField(decimal_places=2, default='0.00', max_digits=12, verbose_name='بدهی :')),
                ('credit', models.DecimalField(decimal_places=2, default='0.00', max_digits=12, verbose_name='اعتبار :')),
                ('currency', models.CharField(blank=True, max_length=255, null=True, verbose_name='واحد پولی :')),
                ('account_holder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hr.employee', verbose_name='صاحب حساب :')),
                ('ledger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.ledger', verbose_name='شماره ردیف :')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.transaction', verbose_name='میادله :')),
            ],
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_no', models.CharField(blank=True, max_length=255, null=True, verbose_name='شماره مرجع :')),
                ('debit', models.DecimalField(decimal_places=2, default='0.00', max_digits=12, verbose_name='بدهی :')),
                ('credit', models.DecimalField(decimal_places=2, default='0.00', max_digits=12, verbose_name='اعتبار :')),
                ('currency', models.CharField(blank=True, max_length=255, null=True, verbose_name='واحد پولی ')),
                ('entry_date', django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='تاریخ ورود :')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.transaction', verbose_name='مبادله')),
            ],
            options={
                'verbose_name': '(اصلاحی) ثبتهای اصلاحی دفتر',
                'verbose_name_plural': '(اصلاحی) ثبتهای اصلاحی دفتر',
            },
        ),
    ]
