# Generated by Django 3.2.5 on 2021-09-04 10:06

from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hr', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enterance_date', django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='تاریخ ورود ')),
                ('enterance_time', models.TimeField(blank=True, null=True, verbose_name='زمان ورود ')),
                ('deperature_date', django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='تاریخ خروج ')),
                ('deperature_time', models.TimeField(blank=True, null=True, verbose_name='زمان خروج ')),
                ('entry_card_status', models.CharField(blank=True, choices=[('accept', 'accept'), ('deny', 'deny')], max_length=32, verbose_name='وضعیت کارت ورود ')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='نظرات ')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hr.employee', verbose_name='کارمند ')),
            ],
            options={
                'verbose_name': 'حضور غیاب',
                'verbose_name_plural': 'حضور غیاب',
            },
        ),
        migrations.CreateModel(
            name='LeaveApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=255, null=True, verbose_name='موضوع ')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات ')),
                ('date_from', django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='از تاریخ ')),
                ('time_from', models.TimeField(blank=True, null=True, verbose_name='از زمان ')),
                ('end_date', django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='تاریخ خاتمه ')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='زمان خاتمه ')),
                ('total_in_hrs', models.CharField(blank=True, max_length=255, null=True, verbose_name='مجموع زمان همکاری ')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='نظرات ')),
                ('status', models.CharField(blank=True, choices=[('approve', 'approve'), ('reject', 'reject')], max_length=32, verbose_name='وضعیت ')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='LeaveApplicant', to='hr.employee', verbose_name='کارمند ')),
                ('hr_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='HRManagerProcess', to='hr.employee', verbose_name='مدیر منابع انسانی ')),
            ],
            options={
                'verbose_name': 'درخواست خاتمه ی همکاری',
                'verbose_name_plural': 'درخواست های خاتمه ی همکاری',
            },
        ),
        migrations.CreateModel(
            name='LeaveApplicationDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='نظرات ')),
                ('comment_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CommentBy', to='hr.employee', verbose_name='نظر داده شده توسط ')),
                ('leave_application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='LeaveApplicationDetails', to='attendance.leaveapplication', verbose_name='درخواست خروج از کار ')),
            ],
            options={
                'verbose_name': 'جزییات درخواست خاتمه ی همکاری',
                'verbose_name_plural': 'جزییات درخواست های خاتمه ی همکاری',
            },
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(blank=True, choices=[('Official', 'Official'), ('Casual', 'Casual')], max_length=32, verbose_name='نحوه ی قطع همکاری ')),
                ('date_from', django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='از تاریخ ')),
                ('time_from', models.TimeField(blank=True, null=True, verbose_name='از زمان ')),
                ('end_date', django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='تاریخ خاتمه ')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='زمان خاتمه ')),
                ('total_in_hrs', models.CharField(blank=True, max_length=255, null=True, verbose_name='مجموه زمان همکاری ')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='نظرات ')),
                ('status', models.CharField(blank=True, choices=[('approve', 'approve'), ('rejected', 'rejected')], max_length=32, verbose_name='وضعیت ')),
                ('leave_application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='LeaveApplication', to='attendance.leaveapplication', verbose_name='درخواست خروج ')),
            ],
            options={
                'verbose_name': 'پایان همکاری',
                'verbose_name_plural': 'پایان همکاری ها',
            },
        ),
        migrations.CreateModel(
            name='in_out_track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_occure', models.TimeField(blank=True, null=True, verbose_name='زمان وقوع ')),
                ('in_out', models.CharField(blank=True, choices=[('in', 'in'), ('out', 'out')], max_length=32, verbose_name='ورود خروج ')),
                ('entry_card_status', models.CharField(blank=True, choices=[('accept', 'accept'), ('deny', 'deny')], max_length=32, verbose_name='وضعیت کارت ورود ')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='نظرات ')),
                ('atendance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='attendance.attendance', verbose_name='حضور ')),
            ],
            options={
                'verbose_name': 'بررسی ورود خروج',
                'verbose_name_plural': 'بررسی ورودها و خروج ها',
            },
        ),
    ]
